<?php

/**
 * Implements hook_menu().
 */
function hellodrupal_menu() {
  $items['hello/world'] = array(
    'title' => 'Hello Drupal',
    'description' => 'The requisite hello-world page.',
    'route_name' => 'hellodrupal.hello',
  );
  $items['hello/%'] = array(
    'title' => 'Hello Person',
    'description' => 'The requisite hello-world page.',
    'route_name' => 'hellodrupal.helloperson',
  );

  return $items;
}


/**
 * Implements hook_theme().
 */
function hellodrupal_theme() {
  return array(
    'hellodrupal_hello' => array(
      'variables' => array('person' => NULL),
      'template' => 'hellodrupal-hello',
    ),
    'hellodrupal_hello_block' => array(
      'variables' => array('person' => NULL),
      'template' => 'hellodrupal-hello-block',
    ),
  );
}
